module.exports = {
  myAnswer: /k$/,
  score: 208,
  shouldMatch: [
    'Mick',
    'Rick',
    'allocochick',
    'backtrick',
    'bestick',
    'candlestick',
    'counterprick',
    'heartsick',
    'lampwick',
    'lick',
    'lungsick',
    'potstick',
    'quick',
    'rampick',
    'rebrick',
    'relick',
    'seasick',
    'slick',
    'tick',
    'unsick',
    'upstick',
  ],
  shouldNotMatch: [
    'Kickapoo',
    'Nickneven',
    'Rickettsiales',
    'billsticker',
    'borickite',
    'chickell',
    'fickleness',
    'finickily',
    'kilbrickenite',
    'lickpenny',
    'mispickel',
    'quickfoot',
    'quickhatch',
    'ricksha',
    'rollicking',
    'slapsticky',
    'snickdrawing',
    'sunstricken',
    'tricklingly',
    'unlicked',
    'unnickeled',
  ]
};
