module.exports = {
  name: 'Four',
  description: 'You can get an extra point by ignoring the name of this ' +
    'level.',
  myAnswer: /(.).\1...\1/,
  score: 199,
  shouldMatch: [
    'Makaraka',
    'Wasagara',
    'degenerescence',
    'desilicification',
    'elevener',
    'hipponosological',
    'homoeomorphy',
    'homologous',
    'ileocolotomy',
    'intervisibility',
    'jararaca',
    'locomotory',
    'micropoikilitic',
    'odontonosology',
    'parhomologous',
    'pogonotomy',
    'promonopolist',
    'protohomo',
    'pseudoprimitivism',
    'tocororo',
    'unintelligibility',
  ],
  shouldNotMatch: [
    'Ludgate',
    'Mitsukurinidae',
    'Ternstroemiaceae',
    'arrhythmical',
    'bleater',
    'energetics',
    'inthrow',
    'mecopterous',
    'multum',
    'naphthalene',
    'nullibicity',
    'observancy',
    'overpunishment',
    'overregularly',
    'overwilily',
    'participator',
    'predisable',
    'reyield',
    'rubeola',
    'traitorlike',
    'unregainable',
  ]
};
