module.exports = {
  name: 'Glob',
  description: '',
  myAnswer: /([rs]m|ness|[^mn]al|de|[rs]y|[st]ly|bia|d|ction|rk|c|ke|er|hwise)$/,
  score: 354,
  shouldMatch: [
    '*err* matches superreform',
    '*falle*ess matches unfallenness',
    '*il*log* matches unphilological',
    '*plen*tud* matches overplenitude',
    '*taiodi* matches pentaiodide',
    '*viceberry matches serviceberry',
    'bowdl* matches bowdlerism',
    'bron*hopleur*sy matches bronchopleurisy',
    'chromatophobia matches chromatophobia',
    'cockneyla* matches cockneyland',
    'colorlessly matches colorlessly',
    'cretefaction matches cretefaction',
    'downrightly matches downrightly',
    'leather* matches leatherbark',
    'mitogenet* matches mitogenetic',
    'palindrom* matches palindromic',
    'parallelepiped matches parallelepiped',
    'primigenial matches primigenial',
    'puppe* matches puppetlike',
    'resurrender matches resurrender',
    'wreathwi* matches wreathwise',
  ],
  shouldNotMatch: [
    '*anapaestical* matches anapaestically',
    '*chegonio matches archegoniophore',
    '*dissoluti* matches dissolutional',
    '*domestica matches domesticality',
    '*expedition matches expedition',
    '*hormog matches hormogonium',
    '*stipular* matches infrastipular',
    '*strabis matches strabismal',
    'cathartica matches cathartically',
    'di matches gerundively',
    'hacean matches zoanthacean',
    'headmist matches headmistress',
    'herwi matches trencherwise',
    'iemphraxia matches cardiemphraxia',
    'kmak matches packmaking',
    'mbable* matches unclimbable',
    'nspi*tor matches inspirator',
    'ocumidi matches pseudocumidine',
    'raretinal* matches intraretinal',
    'tte matches whitterick',
    'uefoliate matches quinquefoliate',
  ]
};
